Feature/lesson2
XedOrg/home-work pull request #1
Opened 2021-11-07 14:58 UTC by XedOrg

2021-11-08 20:40 UTC, Upforup requested changes

2021-11-08 20:40 UTC, Upforup commented on src/main/java/com/sbrf/reboot/Calculator.java
> +    public static double getPow(double x) {
не понятно что должен делать этот метод, в таких случаях помогает документирование.

2021-11-09 13:19 UTC, XedOrg commented on src/main/java/com/sbrf/reboot/Calculator.java
> +    public static double getPow(double x) {
исправил. + добавил описание.

2021-11-16 17:58 UTC, Upforup approved these changes
OK.

2021-11-16 18:54 UTC, merged